import type { Metadata } from "next";
import { Tomorrow } from "next/font/google";
import ReduxProvider from "@/redux/ReduxProvider";
import "./globals.css";

const tomorrow = Tomorrow({
  weight: ["600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${tomorrow.className} antialiased`}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
